//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindMyBook.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class findMyBookEntities1 : DbContext
    {
        public findMyBookEntities1()
            : base("name=findMyBookEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<table_admin> table_admin { get; set; }
        public DbSet<table_author> table_author { get; set; }
        public DbSet<table_book_detail> table_book_detail { get; set; }
        public DbSet<table_book_status> table_book_status { get; set; }
        public DbSet<table_cart> table_cart { get; set; }
        public DbSet<table_customer> table_customer { get; set; }
        public DbSet<table_customer_book_order_details> table_customer_book_order_details { get; set; }
        public DbSet<table_customer_order_book> table_customer_order_book { get; set; }
        public DbSet<table_feedback> table_feedback { get; set; }
        public DbSet<table_orderStatus> table_orderStatus { get; set; }
        public DbSet<table_payment> table_payment { get; set; }
        public DbSet<table_payment_status> table_payment_status { get; set; }
        public DbSet<table_publisher> table_publisher { get; set; }
        public DbSet<tablePayment> tablePayments { get; set; }
    }
}
