//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindMyBook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class table_customer
    {
        public int customer_id { get; set; }

        [Required(ErrorMessage = "First name field is required.")]
        [Display(Name = "First name")]
        public string customer_first_name { get; set; }

        [Required(ErrorMessage = "Last name field is required.")]
        [Display(Name = "Last name")]
        public string customer_last_name { get; set; }

        [Required(ErrorMessage = "Address field is required.")]
        [Display(Name = "Address")]
        public string customer_address { get; set; }

        [Required(ErrorMessage = "Username field is required.")]
        [Display(Name = "Username")]
        public string customer_username { get; set; }

        [Required(ErrorMessage = "Password field is required.")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string customer_password { get; set; }

        [Required(ErrorMessage = "Confirm password field is required.")]
        [Display(Name = "Confirm password")]
        [DataType(DataType.Password)]
        [Compare("customer_password", ErrorMessage = "Password must be same.")]
        [NotMapped]
        public string confirm_password { get; set; }

        [Required(ErrorMessage = "Email field is required.")]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]
        public string email { get; set; }

        public System.DateTime account_creation_date { get; set; }

        [Required(ErrorMessage = "Phone number field is required.")]
        [Display(Name = "Phone number")]
        [StringLength(10, ErrorMessage = "Phone number must be 10 digits.")]
        public string customer_phone_number { get; set; }

        [Display(Name = "Customer profile image")]
        public string customer_image { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
