//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindMyBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_payment
    {
        public int payment_method_id { get; set; }
        public string payment_method { get; set; }
    }
}
