//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindMyBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_cart
    {
        public int cart_id { get; set; }
        public int customer_id_FK { get; set; }
        public int book_id_FK { get; set; }
        public Nullable<int> confirmation_status { get; set; }
    }
}
