//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindMyBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_customer_book_order_details
    {
        public int customer_book_order_detail_id { get; set; }
        public Nullable<int> book_id_FK { get; set; }
        public Nullable<double> book_price { get; set; }
        public Nullable<int> book_qty { get; set; }
        public string discount { get; set; }
        public Nullable<int> order_id_FK { get; set; }
        public Nullable<double> total_price { get; set; }
    }
}
