//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindMyBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tablePayment
    {
        public int payment_id { get; set; }
        public int order_id_FK { get; set; }
        public double payment_amount { get; set; }
        public int payment_method_id_FK { get; set; }
        public System.DateTime payment_date { get; set; }
        public int payment_status_id_FK { get; set; }
    }
}
