//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindMyBook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class table_book_status
    {
        public int book_status_id { get; set; }

        [Required(ErrorMessage = "Book status field is required")]
        [Display(Name = "Book status")]
        public string book_status { get; set; }
    }
}
