//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindMyBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_customer_order_book
    {
        public int order_id { get; set; }
        public System.DateTime order_date { get; set; }
        public System.DateTime delivery_date { get; set; }
        public int customer_id_FK { get; set; } // Assume as customer_id_FK equals to cart_id
        public double total_price { get; set; }
        public int order_status_id_FK { get; set; }
        public int feedback_id_FK { get; set; }
        public int payment_id_FK { get; set; }
    }
}
