//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindMyBook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class table_author
    {
        [Display(Name = "Author ID")]
        public int author_id { get; set; }

        [Required(ErrorMessage = "Author name field is required.")]
        [Display(Name = "Author Name")]
        public string author_name { get; set; }

        [Required(ErrorMessage = "Author Education field is required.")]
        [Display(Name = "Author Education")]
        public string author_education { get; set; }

        [Required(ErrorMessage = "Author Country field is required.")]
        [Display(Name = "Author's Country")]
        public string author_country { get; set; }

        [Required(ErrorMessage = "Number of Published Books field is required.")]
        [Display(Name = "Number of Published Books")]
        public int number_of_published_books { get; set; }
    }
}
