//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindMyBook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class table_admin
    {
        public int admin_id { get; set; }

        [Required(ErrorMessage = "First name field is required.")]
        [Display(Name = "First name")]
        public string first_name { get; set; }

        [Required(ErrorMessage = "Last name field is required.")]
        [Display(Name = "Last name")]
        public string last_name { get; set; }

        [Required(ErrorMessage = "Email field is required.")]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]
        public string email { get; set; }

        [Required(ErrorMessage = "Phone number field is required.")]
        [Display(Name = "Phone number")]
        [StringLength(10, ErrorMessage = "Phone number must be 10 digits.")]
        public string phone_number { get; set; }

        [Required(ErrorMessage = "Username field is required.")]
        [Display(Name = "Username")]
        public string username { get; set; }

        [Required(ErrorMessage = "Password field is required.")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string password { get; set; }

        [Required(ErrorMessage = "Password field is required.")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [Compare("password", ErrorMessage = "Password must be same.")]
        [NotMapped]
        public string confirm_password { get; set; }

    }
}
